<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProcessSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('processes')->insert([
            [
                'nama' => 'GULAI AYAM',
                'image' => 'GULAI_AYAM.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM GORENG BUMBU',
                'image' => 'AYAM_GORENG_BUMBU.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM POP',
                'image' => 'AYAM_POP.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM MASAK HIJAU',
                'image' => 'AYAM_MASAK_HIJAU.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM GORENG BALADO',
                'image' => 'AYAM_GORENG_BALADO.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM KECAP',
                'image' => 'AYAM_KECAP.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM PANGGANG',
                'image' => 'AYAM_PANGGANG.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM RICA-RICA',
                'image' => 'AYAM_RICA-RICA.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'AYAM PANIR',
                'image' => 'AYAM_PANIR.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'RANDANG AYAM',
                'image' => 'RANDANG_AYAM.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'OPOR AYAM',
                'image' => 'OPOR_AYAM.jpg',
                'no_jenis' => 1,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'DENDENG KERING',
                'image' => 'DENDENG_KERING.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'DENDENG LAMBOK',
                'image' => 'DENDENG_LAMBOK.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'DENDENG PARU',
                'image' => 'DENDENG_PARU.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'RENDANG DAGING',
                'image' => 'RENDANG_DAGING.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'DAGING ASAM PEDAS',
                'image' => 'DAGING_ASAM_PEDAS.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GULAI DAGING MERAH/ PUTIH',
                'image' => 'GULAI_DAGING_MERAH_PUTIH.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GULAI DAGING KAMBING MERAH / PUTIH',
                'image' => 'GULAI_DAGING_KAMBING_MERAH_PUTIH.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GULAI HATI SAPI',
                'image' => 'GULAI_HATI_SAPI.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'DAGING LADA HITAM',
                'image' => 'DAGING_LADA_HITAM.jpg',
                'no_jenis' => 2,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'IKAN ASAM MANIS',
                'image' => 'IKAN_ASAM_MANIS.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'IKAN ASAM PEDAS',
                'image' => 'IKAN_ASAM_PEDAS.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'IKAN LAUT BAKAR',
                'image' => 'IKAN_LAUT_BAKAR.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'IKAN NILA BAKAR',
                'image' => 'IKAN_NILA_BAKAR.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'IKAN PEPES',
                'image' => 'IKAN_PEPES.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'IKAN ACAR KUNING',
                'image' => 'IKAN_ACAR_KUNING.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'IKAN MASAK TAUCO',
                'image' => 'IKAN_MASAK_TAUCO.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GULAI IKAN PAUH',
                'image' => 'GULAI_IKAN_PAUH.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GULAI CUMI',
                'image' => 'GULAI_CUMI.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GULAI UDANG TELUR PUYUH',
                'image' => 'GULAI_UDANG_TELUR_PUYUH.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BELUT GORENG BALADO / HIJAU',
                'image' => 'BELUT_GORENG_BALADO_HIJAU.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'RENDANG BELUT',
                'image' => 'RENDANG_BELUT.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'RENDANG LOKAN',
                'image' => 'RENDANG_LOKAN.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'UDANG GORENG TEPUNG',
                'image' => 'UDANG_GORENG_TEPUNG.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'UDANG GORENG BALADO TELUR PUYUH',
                'image' => 'UDANG_GORENG_BALADO_TELUR_PUYUH.jpg',
                'no_jenis' => 3,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ACAR',
                'image' => 'ACAR.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GADO-GADO',
                'image' => 'GADO-GADO.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SAYUR ASEM',
                'image' => 'SAYUR_ASEM.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GULAI NANGKA',
                'image' => 'GULAI_NANGKA.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'CAH PAKU',
                'image' => 'CAH_PAKU.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'CAPCAY',
                'image' => 'CAPCAY.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ANYANG',
                'image' => 'ANYANG.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ORAK ARIK',
                'image' => 'ORAK_ARIK.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LALAPAN',
                'image' => 'LALAPAN.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'URAP',
                'image' => 'URAP.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'PECEL',
                'image' => 'PECEL.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'CAH KANGKUNG',
                'image' => 'CAH_KANGKUNG.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'DAUN UBI LAPIS',
                'image' => 'DAUN_UBI_LAPIS.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'CAH JAGUNG',
                'image' => 'CAH_JAGUNG.jpg',
                'no_jenis' => 4,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ANEKA BOLU KUKUS',
                'image' => 'ANEKA_BOLU_KUKUS.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BOLU BAKING / PANDAN /MARMAR',
                'image' => 'BOLU_BAKING_PANDAN_MARMAR.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BROWNIES BAKAR COKLAT',
                'image' => 'BROWNIES_BAKAR_COKLAT.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BROWNIES KUKUS PANDAN',
                'image' => 'BROWNIES_KUKUS_PANDAN.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BROWNIES KUKUS COKLAT',
                'image' => 'BROWNIES_KUKUS_COKLAT.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BROWNIES KUKUS LAPIS',
                'image' => 'BROWNIES_KUKUS_LAPIS.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'CAKE PANDAN',
                'image' => 'CAKE_PANDAN.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'CAKE PISANG',
                'image' => 'CAKE_PISANG.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'CAKE PUDING COCKTAIL',
                'image' => 'CAKE_PUDING_COCKTAIL.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'COCO SLAIS CAKE',
                'image' => 'COCO_SLAIS_CAKE.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SUS',
                'image' => 'SUS.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BOLU GULUNG ORANGE / PANDAN / COKLAT /STRAWBARRY',
                'image' => 'BOLU_GULUNG_ORANGE_PANDAN_COKLAT_STRAWBERRY.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BOLU GULUNG MINI',
                'image' => 'BOLU_GULUNG_MINI.jpg',
                'no_jenis' => 5,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ROTI MISES',
                'image' => 'ROTI_MISES.jpg',
                'no_jenis' => 6,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ROTI COKLAT KEJU',
                'image' => 'ROTI_COKLAT_KEJU.jpg',
                'no_jenis' => 6,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ROTI KELAPA JAGUNG',
                'image' => 'ROTI_KELAPA_JAGUNG.jpg',
                'no_jenis' => 6,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ROTI ISI FILLO COKLAT',
                'image' => 'ROTI_ISI_FILLO_COKLAT.jpg',
                'no_jenis' => 6,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ROTI COKLAT PISANG',
                'image' => 'ROTI_COKLAT_PISANG.jpg',
                'no_jenis' => 6,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ROTI ISI LEPATTA PANDAN',
                'image' => 'ROTI_ISI_LEPATTA_PANDAN.jpg',
                'no_jenis' => 6,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'GORENG PISANG CRISPY',
                'image' => 'GORENG_PISANG_CRISPY.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'KACIMUIH',
                'image' => 'KACIMUIH.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'KETAN SRIKAYA',
                'image' => 'KETAN_SRIKAYA.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'KUE LUMPUR KENTANG/ PANDAN',
                'image' => 'KUE_LUMPUR_KENTANG_PANDAN.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LAPEK BUGIH',
                'image' => 'LAPEK_BUGIH.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LAPEK PISANG',
                'image' => 'LAPEK_PISANG.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LAPIS SINGKONG PELANGI',
                'image' => 'LAPIS_SINGKONG_PELANGI.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LAPIS BERAS / LAPIS KANJI',
                'image' => 'LAPIS_BERAS_LAPIS_KANJI.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LOPIS',
                'image' => 'LOPIS.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'MANGKUK UBI UNGU',
                'image' => 'MANGKUK_UBI_UNGU.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ONDE- ONDE ISI 3',
                'image' => 'ONDE-ONDE_ISI_3.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'ONDE – ONDE WIJEN',
                'image' => 'ONDE–ONDE_WIJEN.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SERABI',
                'image' => 'SERABI.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SEMERMENDEM',
                'image' => 'SEMERMENDEM.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LEMPER',
                'image' => 'LEMPER.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SINGKONG THAILAND',
                'image' => 'SINGKONG_THAILAND.jpg',
                'no_jenis' => 7,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'BAKWAN UDANG REBON',
                'image' => 'BAKWAN_UDANG_REBON.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'KROKET KENTANG',
                'image' => 'KROKET_KENTANG.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'KROKET SINGKONG',
                'image' => 'KROKET_SINGKONG.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LEMPER GORENG',
                'image' => 'LEMPER_GORENG.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'LUMPIA SAYUR',
                'image' => 'LUMPIA_SAYUR.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'MARTABAK MINI TELOR',
                'image' => 'MARTABAK_MINI_TELOR.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'PASTEL',
                'image' => 'PASTEL.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SCHOTEL JAGUNG',
                'image' => 'SCHOTEL_JAGUNG.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SKOTEL BIHUN',
                'image' => 'SKOTEL_BIHUN.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SKOTEL TAHU',
                'image' => 'SKOTEL_TAHU.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'RISOLES SAYUR',
                'image' => 'RISOLES_SAYUR.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'RISOLES SEGITIGA SAYUR',
                'image' => 'RISOLES_SEGITIGA_SAYUR.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'MARTABAK MINI TELUR',
                'image' => 'MARTABAK_MINI_TELUR.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'TAHU ISI',
                'image' => 'TAHU_ISI.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'MARTABAK SHANGHAI',
                'image' => 'MARTABAK_SHANGHAI.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ], [
                'nama' => 'SWI KIAU',
                'image' => 'SWI_KIAU.jpg',
                'no_jenis' => 8,
                'desc' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem sunt tempora quae architecto quia numquam sapiente incidunt neque odit est consectetur ut veritatis eum voluptatibus, adipisci reiciendis minus? Eius, aperiam.',
                'created_at' => today(),
                'updated_at' => today(),
            ]
        ]);
    }
}
